### ISSUE TITLE
_support.scss : Calling call() with a string has been deprecated in Sass 3.5 and will break in Sass 4.0

### ISSUE THREAD

**Issue by tim-durrant** [oddbird/susy#625]
I discovered this today when I upgraded to Sass 3.5, and received several deprecation warnings.  There will be a code fix required as follows:

Line 70 in **susy/sass/susy/output/support/_support.scss**

`        $_pass: call(unquote("#{$_type}-exists"), $_i);`

needs to be modified to

`        $_pass: call(get-function(unquote("#{$_type}-exists")), $_i);`

_More details: http://blog.sass-lang.com/posts/809572-sass-35-release-candidate_

**Comment by mirisuzanne** [comment]
Yeah, In order to be compatible with both pre and post 3.5, we need to do a bit more workaround. I've [fixed that in Susy 3](https://github.com/oddbird/susy/pull/600/commits/15c251dcf5ca8b45fc0fa59d4fa49b2023a8ca4e#diff-65a950017833d86c70a5e821971baa0fR20), hopefully out soon, but I'd love a PR for something similar in Susy 2. Interested in submitting a patch?

**Comment by tim-durrant** [comment]
Sure.  Actually a newbie to Github  :-)  Have you got any specific procedures to follow for a patch or is there generic doco online?  Cheers!

**Comment by mirisuzanne** [comment]
Oh, fun learning time for you! I'm sure there are articles, but I don't know off-hand. I'm also happy to help how I can. How experienced are you with Git generally? The steps are (roughly):

1. "Fork" this repository with the button up top.
2. On your own fork of the project, use the "clone or download" button to get the address, and run `git clone <address> <local-directory>` (replacing those <bits>) in a terminal window to get the local version.
3. Run `git branch -b <branch-name>` to create a new branch
4. make your changes in the `sass` dir!! (add tests if you can, in the `test/sass` dir)
5. `rake test` to make sure all the tests are passing.
6. `git add .; git commit -m '<explain the commit>'` to commit your changes
7. `git push -u origin <branch-name>` to put it all back on github
8. Hit the `new pull request` button on your github fork — select our repo/master-branch as the "base", and your repo/new-branch as the "head"
9. Submit your pull request!

So I gave you a lot of detail on the git steps without much real detail on the git steps... Let me know if you have any questions, or get stuck. I'm happy to expand or clarify if I can.

**Comment by Jameskmonger** [comment]
@mirisuzanne Does this need to be done against the `susytwo` branch in order to fix it for v2?

**Comment by mirisuzanne** [comment]
@Jameskmonger that's right, though I'm not sure the solution above is the best (see http://oddbird.net/2017/03/30/safe-get/). If you want to do that, I'm happy to consider a pull request! Thanks!

**Comment by mirisuzanne** [comment]
Fixed by 8e5dab9259077d6c0

**Comment by brograhamer** [comment]
Hey, I'm sorry to reopen this request @mirisuzanne and @nigelheap. This issue still stands. Experienced the message today for the first time. I applied the patch but still receiving the error. Any thoughts?

**Comment by mirisuzanne** [comment]
@brograhamer Can you provide a stripped-down example (preferably in a GitHub repo) that demonstrates the error? I'm not able to reproduce it locally.

**Comment by brograhamer** [comment]
@mirisuzanne working on it, I'll either post back today with incompatibilities with other components, a patch, or a stripped down project for you to check. Sorry for the delay.

**Comment by mirisuzanne** [comment]
No problem, that's what stripped-down examples are for - half the time they solve the problem. :) Thanks for the update!
